<a href="https://colab.research.google.com/github/vidyasagarcrj/Sentiment_Analysis_scratch/blob/main/Another_copy_of_Questions_HuggingFace_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Problem Statement

1. 🛠️ The overall problem is to develop a text classification system using a pre-trained DistilBert model that can accurately predict categories based on textual input.

2. 📝 The input feature, denoted as 'X', consists of raw text strings sourced from a dataset, which the model processes to predict categorical labels.

3. 🎯 The target variable, referred to as 'label', represents the actual categories of the text, which are used to train the model and evaluate its accuracy.

4. 📊 The model's performance is assessed through metrics such as the confusion matrix and accuracy, comparing the predicted labels against the actual labels.

5. 🔧 The project involves not only fine-tuning a pre-trained language model on a specific dataset but also validating its effectiveness on both a smaller sample and a larger subset to ensure robustness and scalability of the predictions.

#Install the necessary libraries



1. **Install Accelerate**:
2. **Install Transformers and Datasets**:
3. **Upgrade PyArrow**:

Import Libraries

1. **Import Standard Data Science Libraries**:
3. **Import PyTorch and Transformers for NLP**:



In [ ]:
## Write your code here

In [ ]:
!pip -q install accelerate -U
!pip -q install transformers[torch]
!pip -q install datasets
#Restart after installing

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 480.6/480.6 kB 15.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 8.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.3/179.3 kB 12.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 11.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 17.1 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2024.10.0 requires fsspec==2024.10.0, but you have fsspec 2024.9.0 which is incompatible.


# Import Emotions Data. Target variable is 'Label'

Import the data from https://raw.githubusercontent.com/venkatareddykonasani/Datasets/master/Final_Emotion_Data/five_emotions_data.csv

Display the first few rows of the dataset to understand its structure

In [ ]:
## Write your code here

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from transformers import pipeline

In [ ]:
# Textwrp function to display the output in a better format
# This is an optional function, you can ignore it
from IPython.display import HTML, display

def wrap_display():
  display(HTML('''
  <style>
    pre {
        white-space: pre-wrap;
    }
  </style>
  '''))
get_ipython().events.register('pre_run_cell', wrap_display)

In [ ]:
import pandas as pd
emotion_data=pd.read_csv("https://raw.githubusercontent.com/venkatareddykonasani/Datasets/master/Final_Emotion_Data/five_emotions_data.csv")

In [ ]:
emotion_data.head()

Id    Emotion                                               Text  label
0   1    sadness                            i didnt feel humiliated      3
1   2    sadness  i can go from feeling so hopeless to so damned...      3
2   4       love  i am ever feeling nostalgic about the fireplac...      1
3   6    sadness  ive been feeling a little burdened lately wasn...      3
4   9  happiness  i have been with petronas for years i feel tha...      0

In [ ]:
# Distil bert model
from transformers import pipeline
distilbert_model = pipeline(task="text-classification",
                            model="distilbert-base-uncased",
                            )

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

Device set to use cuda:0


In [ ]:
sample_data=emotion_data.sample(3000, random_state=77)
sample_data["Text"]=sample_data["Text"].apply(lambda x: " ".join(x.split()[:350]))
sample_data["bert_predicted"] = sample_data["Text"].apply(lambda x: distilbert_model(x)[0]["label"])
#Default prediction is not a number LABEL_1, LABEL_0
sample_data["bert_predicted_num"]=sample_data["bert_predicted"].apply(lambda x: x[-1])
sample_data["bert_predicted_num"] = sample_data["bert_predicted_num"].astype(int)
sample_data.head()

Id  Emotion                                               Text  \
3568    5036     love  i just feel that there is too much too many pa...   
30732  40424  sadness  I was right, street market + rain = not a good...   
14641  20109  neutral                            off to revise again now   
5896    8341  sadness  i feel ungrateful for being unhappy but i cant...   
33874  44537  neutral                     @twittess j� passo o link   

       label bert_predicted  bert_predicted_num  
3568       1        LABEL_0                   0  
30732      3        LABEL_0                   0  
14641      2        LABEL_0                   0  
5896       3        LABEL_0                   0  
33874      2        LABEL_0                   0

# Use distilbert model without finetunung

Here are concise instructions to write and execute the Python code you provided, which utilizes a pre-trained DistilBERT model from the `transformers` library for text classification without fine-tuning:

Step 1: Install and Import Libraries
1. **Install the necessary Python packages** if they're not already installed:

2. **Import the libraries** in your Python script:


 Step 2: Set Up the DistilBERT Model
1. **Initialize the DistilBERT pipeline** for text classification. Ensure you have GPU support (CUDA) if available:


 Step 3: Prepare and Predict with Your Dataset
1. **Sample and preprocess the dataset**:
   - Assuming `emotions_data` is already loaded:

2. **Classify text** using the model and extract predictions:


Step 4: Evaluate Model Performance
1. **Calculate and print the confusion matrix** and accuracy:




In [ ]:
## Write your code here

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(sample_data["label"], sample_data["bert_predicted_num"])
print(cm)
accuracy=cm.diagonal().sum()/cm.sum()
print(accuracy)

[[755   0   0   0   0]
 [334   0   0   0   0]
 [609   0   0   0   0]
 [725   0   0   0   0]
 [577   0   0   0   0]]
0.25166666666666665


In [ ]:
from transformers import DistilBertTokenizer, DistilBertForSequenceClassification, Trainer, TrainingArguments
from transformers import Trainer, TrainingArguments
from datasets import load_dataset, DatasetDict, ClassLabel, Dataset
import pandas as pd
from sklearn.model_selection import train_test_split
import torch

# Finetuning the model with our data


1. Begin by importing necessary libraries including `DistilBertTokenizer` and `DistilBertForSequenceClassification` from `transformers`, `load_dataset`, `DatasetDict`, `ClassLabel`, and `Dataset` from `datasets`, `pandas`, `train_test_split` from `sklearn.model_selection`, and `torch`.

2. Load your sample data into a pandas DataFrame, `sample_data`.

3. Convert the DataFrame into a `Dataset` object using `Dataset.from_pandas()` method.

4. Split the data into training and testing sets using the `train_test_split` method from the `datasets` library, setting aside 20% of the data for testing.

5. Create a `DatasetDict` to organize the datasets into 'train' and 'test' subsets.

6. Load the `DistilBertTokenizer` from the `transformers` library using the pretrained 'distilbert-base-uncased' model.

7. Set the tokenizer's padding token to the end-of-sequence token and update the padding token ID accordingly. Add a special padding token '[PAD]' to the tokenizer.

8. Define a function, `tokenize_function`, that tokenizes the texts in the dataset. Ensure the texts are padded to a maximum length of 100 characters and truncated if necessary.

9. Apply the `tokenize_function` to the datasets using the `.map()` method with `batched=True` to process batches of texts at once.

In [ ]:
#Write your code here

In [ ]:
#The target variable must be named as "label" - Verify it, before proceeding
print(sample_data.columns)

Index(['Id', 'Emotion', 'Text', 'label', 'bert_predicted',
       'bert_predicted_num'],
      dtype='object')


In [ ]:
sample_data.count()

Id                    3000
Emotion               3000
Text                  3000
label                 3000
bert_predicted        3000
bert_predicted_num    3000
dtype: int64

In [ ]:
Sample_data = Dataset.from_pandas(sample_data)
# Split the dataset into training and testing sets
train_test_split = Sample_data.train_test_split(test_size=0.2)  # 80% training, 20% testing
dataset = DatasetDict({
    'train': train_test_split['train'],
    'test': train_test_split['test']
})
dataset

DatasetDict({
    train: Dataset({
        features: ['Id', 'Emotion', 'Text', 'label', 'bert_predicted', 'bert_predicted_num', '__index_level_0__'],
        num_rows: 2400
    })
    test: Dataset({
        features: ['Id', 'Emotion', 'Text', 'label', 'bert_predicted', 'bert_predicted_num', '__index_level_0__'],
        num_rows: 600
    })
})

In [ ]:
# Load the tokenizer
tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')

# Padding
tokenizer.pad_token = tokenizer.eos_token
tokenizer.pad_token_id = tokenizer.eos_token_id
tokenizer.add_special_tokens({'pad_token': '[PAD]'} )

def tokenize_function(examples):
    return tokenizer(examples["Text"], padding="max_length", truncation=True, max_length=512)
tokenized_datasets = dataset.map(tokenize_function, batched=True)

Map:   0%|          | 0/2400 [00:00<?, ? examples/s]

Map:   0%|          | 0/600 [00:00<?, ? examples/s]

In [ ]:
model = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased',
                                                            num_labels=5,
                                                            pad_token_id=tokenizer.eos_token_id) # Adjust num_labels as needed
model

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (li

In [ ]:
training_args = TrainingArguments(
    output_dir="./results_bert_custom",
    num_train_epochs=1,
    logging_dir="./logs_bert_custom",
    evaluation_strategy="epoch",
)

# Initialize the Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets['train'],
    eval_dataset=tokenized_datasets['test'],
)

# Start training
trainer.train()

/usr/local/lib/python3.10/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(


TrainOutput(global_step=100, training_loss=1.0750191497802735, metrics={'train_runtime': 50.0978, 'train_samples_per_second': 15.969, 'train_steps_per_second': 1.996, 'total_flos': 105979588608000.0, 'train_loss': 1.0750191497802735, 'epoch': 1.0})

In [ ]:
# Define the directory where you want to save your model and tokenizer
model_dir = "/content/Distilbert_emotion_model_v4"

# Save the model
model_v2.save_pretrained(model_dir)

# Save the tokenizer
tokenizer.save_pretrained(model_dir)

#Save the model with
#trainer.save_model('Distilbert_emotion_model_10k')

('/content/Distilbert_emotion_model_v4/tokenizer_config.json',
 '/content/Distilbert_emotion_model_v4/special_tokens_map.json',
 '/content/Distilbert_emotion_model_v4/vocab.txt',
 '/content/Distilbert_emotion_model_v4/added_tokens.json')

## Load and Train the model

1. Load the `DistilBertForSequenceClassification` model from the `transformers` library, using the pretrained 'distilbert-base-uncased' model. Specify `num_labels` based on your classification needs and set `pad_token_id` to the tokenizer's end-of-sequence token ID.

2. Set up the training configuration using `TrainingArguments`. Define an `output_dir` for storing training results, set `num_train_epochs` for the number of training epochs, specify a `logging_dir` for training logs, and choose `evaluation_strategy` as 'epoch' to perform evaluations at the end of each epoch.

3. Initialize a `Trainer` object with the model, training arguments, and datasets for training and evaluation. Specify the training dataset using `tokenized_datasets['train']` and the evaluation dataset as `tokenized_datasets['test']`.

4. Begin the training process by invoking the `train()` method on the `Trainer`.

5. Specify a directory where you want to save both the trained model and the tokenizer, e.g., "./distilbert_finetuned".

6. Save the trained model and tokenizer to the specified directory using the `save_pretrained()` method for both the model and tokenizer.

7. Additionally, save the model to another directory or under another name using the `save_model()` method of the `Trainer`.

8. Compress the model directory into a ZIP file using a zip utility, specifying the target directory and the name for the ZIP file, e.g., "distilbert_finetuned_10k.zip".

In [ ]:
def make_prediction(text):
  new_complaint=text
  inputs=tokenizer(new_complaint, return_tensors="pt")
  inputs = inputs.to(torch.device("cuda:0"))
  outputs=model(**inputs)
  predictions=outputs.logits.argmax(-1)
  predictions=predictions.detach().cpu().numpy()
  return(predictions)

sample_data["finetuned_predicted"]=sample_data["Text"].apply(lambda x: make_prediction(str(x))[0])
sample_data.sample(10)

Id    Emotion                                               Text  \
15277  20896      worry  Going to see Star Trek (again) tomorrow night ...   
9967   14056       love  i have this insatiable desire to plant and cle...   
37012  48681  happiness  @anyamarina that was funny! LOVED IT! I almost...   
38131  50158  happiness                  @cherrybaby2001 Glad you like it!   
34679  45601      worry                          I am chillin w/ my homies   
13105  18191  happiness  @carocat Nooo But hey you're back next week! A...   
9795   13818    sadness  i made justin feel pretty miserable last night...   
39564  52009  happiness  @nak1a &quot;If there's a camel up a hill&quot...   
17212  23319      worry  hates not being able to see his monitor. I hav...   
9768   13772  happiness  i have become a mother and my body has changed...   

       label bert_predicted  bert_predicted_num  finetuned_predicted  
15277      4        LABEL_0                   0                    4  
9967       1        LABEL_0                   0                    0  
37012      0        LABEL_0                   0                    4  
38131      0        LABEL_0                   0                    2  
34679      4        LABEL_0                   0                    4  
13105      0        LABEL_0                   0                    2  
9795       3        LABEL_0                   0                    3  
39564      0        LABEL_0                   0                    2  
17212      4        LABEL_0                   0                    3  
9768       0        LABEL_0                   0                    0

In [ ]:
from sklearn.metrics import confusion_matrix
# Create the confusion matrix
cm1 = confusion_matrix(sample_data["label"], sample_data["finetuned_predicted"])
print(cm1)
accuracy1=cm1.diagonal().sum()/cm1.sum()
print(accuracy1)

[[133   0  77  18  29]
 [ 31   0  44   6  16]
 [  3   0 144   7  40]
 [  6   0  35 136  62]
 [  5   0  74  28 106]]
0.519


## Make Predictions

1. Define a function, `make_prediction`, which takes a single text string as input. Inside this function:
   - Tokenize the text using your pretrained tokenizer. Specify that tensors should be returned as PyTorch tensors (`return_tensors="pt"`).
   - Send the tokenized inputs to a CUDA device for GPU acceleration.
   - Pass the inputs to your pretrained model and obtain the outputs.
   - Extract the logits from the outputs and determine the predicted class by finding the index of the maximum logit value.
   - Convert the prediction tensor from GPU to CPU and transform it into a numpy array.
   - Return the prediction.

2. Apply the `make_prediction` function to the "Text" column of your `sample_data` DataFrame, extracting the first element of the returned array to a new column named `finetuned_predicted`.

3. Calculate the confusion matrix using `confusion_matrix` from `sklearn.metrics`, comparing the actual labels and the predicted labels from your DataFrame. Print the resulting confusion matrix.

4. Compute and print the accuracy of your predictions by dividing the sum of the diagonal elements of the confusion matrix by the total number of predictions.

5. Select a large subset (e.g., 40,000 samples) from another dataset (assumed to be `emotions_data` here), using a fixed random state for reproducibility.

6. Apply the `make_prediction` function to the "Text" column of this large dataset, storing the results in a new column named `finetuned_predicted`.

7. Calculate and print the confusion matrix for this larger dataset to compare the predicted labels against the actual labels.

8. Compute and print the accuracy for this dataset in the same manner as described above.

In [ ]:
#Code to donwloading the distilbert model
#!gdown --id 1785J3ir19RaZP3ebbFvWUX88PMaBouro -O Distilbert_emotion_model.zip
#!unzip -o -j Distilbert_emotion_model.zip -d Distilbert_emotion_model

model_v4 = DistilBertForSequenceClassification.from_pretrained('/content/Distilbert_emotion_model_v4')
#model_v4.to("cuda:0")

In [ ]:
def make_prediction(text):
  new_complaint=text
  inputs=tokenizer(new_complaint, return_tensors="pt")
  inputs = inputs.to(torch.device("cuda:0"))
  outputs=model_v2(**inputs)
  predictions=outputs.logits.argmax(-1)
  predictions=predictions.detach().cpu().numpy()
  return(predictions)

sample_data["finetuned_predicted"]=sample_data["Text"].apply(lambda x: make_prediction(str(x))[0])
sample_data.sample(10)

Id    Emotion                                               Text  \
19689  26410    sadness  Bad day! Work's TOO stressful...been involved ...   
2652    3744  happiness  i mean as a group thing it felt good to get in...   
5934    8396    sadness                              i do not feel as ugly   
27688  36423  happiness                   @eltonmcmanus &amp; to you matey   
14731  20227      worry  ive made a terrible mistake i need an auto sav...   
22157  29463    sadness  Apparently it's 21 degrees in Kilkenny now! An...   
10117  14260    sadness  i feel fake sharing the joyful and creative pu...   
9754   13752  happiness                  i feel appreciative of everything   
25247  33383    sadness  Puzzled by people's mood swings... it makes me...   
30657  40329    neutral  incredibly cliched at this point, but May the ...   

       label bert_predicted  bert_predicted_num  finetuned_predicted  
19689      3        LABEL_0                   0                    4  
2652       0        LABEL_0                   0                    0  
5934       3        LABEL_0                   0                    3  
27688      0        LABEL_0                   0                    0  
14731      4        LABEL_0                   0                    4  
22157      3        LABEL_0                   0                    3  
10117      3        LABEL_0                   0                    3  
9754       0        LABEL_0                   0                    0  
25247      3        LABEL_0                   0                    3  
30657      2        LABEL_0                   0                    2

In [ ]:
from sklearn.metrics import confusion_matrix
# Create the confusion matrix
cm1 = confusion_matrix(sample_data["label"], sample_data["finetuned_predicted"])
print(cm1)
accuracy1=cm1.diagonal().sum()/cm1.sum()
print(accuracy1)

[[667  41  30   4  13]
 [ 42 262  16   2  12]
 [ 23   7 517  11  51]
 [  7   3  21 615  79]
 [  8   6  59  24 480]]
0.847


In [ ]:
model_path = "/content/Distilbert_emotion_model_new"

In [ ]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

In [ ]:
tokenizer = AutoTokenizer.from_pretrained(model_path)
model_v2 = AutoModelForSequenceClassification.from_pretrained(model_path)

In [ ]:
model_v2.eval()

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (li

In [ ]:
training_args = TrainingArguments(
    output_dir="./results_bert_custom",
    num_train_epochs=3,
    logging_dir="./logs_bert_custom",
    evaluation_strategy="epoch",
)

# Initialize the Trainer
trainer = Trainer(
    model=model_v2,
    args=training_args,
    train_dataset=tokenized_datasets['train'],
    eval_dataset=tokenized_datasets['test'],
)

# Start training
trainer.train()

/usr/local/lib/python3.10/dist-packages/transformers/training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(


TrainOutput(global_step=900, training_loss=0.7588437906901042, metrics={'train_runtime': 399.0135, 'train_samples_per_second': 18.045, 'train_steps_per_second': 2.256, 'total_flos': 953816297472000.0, 'train_loss': 0.7588437906901042, 'epoch': 3.0})

In [ ]:
sample_data_large=emotion_data.sample(n=1000, random_state=56)
sample_data_large["finetuned_predicted"]=sample_data_large["Text"].apply(lambda x: make_prediction(str(x)[:350])[0])

In [ ]:
from sklearn.metrics import confusion_matrix
# Create the confusion matrix
cm1 = confusion_matrix(sample_data_large["label"], sample_data_large["finetuned_predicted"])
print(cm1)
accuracy1=cm1.diagonal().sum()/cm1.sum()
print(accuracy1)

[[161  23  30  13  11]
 [ 36  62  19   4   6]
 [ 23   9 133  11  41]
 [  8   5  17 144  54]
 [ 18   8  40  24 100]]
0.6


In [ ]:
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

In [ ]:
!pip install transformers huggingface_hub


In [ ]:
from huggingface_hub import login

# Replace 'your_token_here' with your Hugging Face token
login(token="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")


In [ ]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer
from huggingface_hub import HfApi

# Path to your fine-tuned model directory
model_path = "/content/Distilbert_emotion_model_v4"

# Load the model and tokenizer from the directory
model = AutoModelForSequenceClassification.from_pretrained(model_path)
tokenizer = AutoTokenizer.from_pretrained(model_path)

# Push the model to Hugging Face Hub
model_name = "SagarVidya/distilbert-emotion-model_v4"  # Replace with your desired repository name
model.push_to_hub(model_name)
tokenizer.push_to_hub(model_name)

print(f"Model uploaded to: https://huggingface.co/{model_name}")


model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

README.md:   0%|          | 0.00/5.17k [00:00<?, ?B/s]

Model uploaded to: https://huggingface.co/SagarVidya/distilbert-emotion-model_v4


In [ ]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer

# Replace with your Hugging Face model repository
model_name = "SagarVidya/distilbert-emotion-model_v4"

# Load the model and tokenizer
model = AutoModelForSequenceClassification.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

# Test inference
text = "I am so happy!"
inputs = tokenizer(text, return_tensors="pt")
outputs = model(**inputs)
print(outputs)


config.json:   0%|          | 0.00/861 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.28k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/711k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/695 [00:00<?, ?B/s]

SequenceClassifierOutput(loss=None, logits=tensor([[ 3.8995,  1.4792, -1.4603, -2.5683, -2.2700]],
       grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)


In [ ]:
Senti_model_2 = pipeline(task="sentiment-analysis",
                         model="SagarVidya/distilbert-emotion-model_v4")

Device set to use cuda:0


In [ ]:
Senti_model_2("After weeks of hard work and countless sleepless nights, I finally achieved my dream job. My parents were so proud, and I couldn't stop smiling as tears of joy streamed down my face.")

[{'label': 'LABEL_0', 'score': 0.9677368402481079}]

In [ ]:
0 - happiness
1 - love
2 - neutral
3 - sadness
4 - worry


In [ ]:
df = pd.DataFrame(emotion_data)

In [ ]:
unique_values = df.unique(df[['Emotion', 'label']].values.ravel())

print("Unique values from both columns:", unique_values)

AttributeError: 'DataFrame' object has no attribute 'unique'